@startuml
title
 <u>Admin View User Information</u>
end title

Swagger -> V1Delegate: View information request
V1Delegate -> UserService: View information request
UserService -> UserRepository: Verify request (userId)
UserRepository -> UserDatabase: Query (userId)
UserDatabase --> UserRepository: Result
UserRepository --> UserService: Result

UserService -> FileService: Read information request(fileId)
FileService -> FileRepository: Read information request(fileId)
FileRepository -> FileDatabase: Query
FileDatabase --> FileRepository: Results
FileRepository --> FileService: Results
FileService --> UserService: Results
UserService --> UserService: Combine information
UserService --> V1Delegate: Combined results
V1Delegate --> Swagger: Combined results
@enduml